### ISSUE TITLE
Incompatible with @amplitude/analytics-browser cookie

### ISSUE THREAD

**Issue by adambullmer** [amplitude/experiment-node-server#15]
## Expected Behavior
Following the documentation [here](https://www.docs.developers.amplitude.com/experiment/sdks/nodejs-sdk/#access-amplitude-cookies) for accessing (and creating) cookies server side, I expect to for this to be compatible with both `amplitude-js` and `@amplitude/analytics-browser` SDKs, or at the very least, supporting the non-deprecated ones.

## Current Behavior
The current AmplitudeCookie class provided by this package only supports the `amplitude-js` cookie format of `amp_<app id>`, and not the new `@amplitude/analytics-browser` format of `AMP_<longer app id>`. The problem is that device IDs will fall out of sync, and user IDs will be lost to the experiment code as they will only exist in the new cookie format.

## Possible Solution
- Update the existing class
  - Allow specifying a new cookie version, defaulting to `1` or `amplitude-js` to maintain current behavior
  - Prefer the new cookie/format, but fall back to any previous formats starting at the supplied cookie version.
  - When setting a cookie, use the same format as was previously found.
  - If a cookie was not found and setting a new cookie, use the new cookie version config to set the appropriate version cookie
- Create an additional class to support the new cookie format and have the sdk consumers be responsible for migration of cookies in a SSR context (not recommended)

## Steps to Reproduce
1. Implement server cookie reading/parsing/setting according to the setup docs [here](https://www.docs.developers.amplitude.com/experiment/sdks/nodejs-sdk/#access-amplitude-cookies)
2. Have a client set the cookie using the new `@amplitude/analytics-browser` SDK.
3. Visit a page that does the above SSR and client stuffs
4. (optional) for fresh sessions, the v1 cookie will have been migrated, and a page refresh will be necessary
5. Observe that 2 amp cookies now exist in multiple formats

## Environment
- JS Client SDK Version: `@amplitude/analytics-browser@npm:1.9.1`
- JS Server SDK Version: `@amplitude/experiment-node-server@npm:1.4.0`
- Installation Method: `yarn@3.2.0` (Node modules linker)
- Browser and Version: Any

**Comment by bgiori** [comment]
Hi @adambullmer,

Thanks for your detailed issue, and sorry for the late response. You're right, the new amplitude TS SDK cookie format is incompatible with the existing code. 

I'll keep this issue open and update it with any news.

Thanks!

**Comment by michal-filip** [comment]
Any update on this one? This issue still bites. Is there some other npm package that would contain the utilities for parsing/generating the newer cookies and would be recommended for usage on the nodejs server?

**Comment by tyiuhc** [comment]
Thank you so much for your patience on this. You can now make use of the new Cookie utilities in v1.7.6 to parse the new format cookies.
