### ISSUE TITLE
have `flagName` back in the cached experiments

### ISSUE THREAD

**Issue by sod** [amplitude/experiment-node-server#19]
We use the contents of `client.cache.getAll()` to render a helper page for QA to assign themself to tests
<img width="518" alt="CleanShot 2023-06-28 at 09 02 10@2x" src="https://github.com/amplitude/experiment-node-server/assets/905328/a5e99933-3c57-4dc3-a663-258f2299cb8d">

We use `variants`, `flagKey` and `flagName`. But `flagName` disappeared in `1.4.0`, nowhere to be found in a cache entry:

<img width="440" alt="CleanShot 2023-06-28 at 09 03 53@2x" src="https://github.com/amplitude/experiment-node-server/assets/905328/7c2dcfd3-6ddc-459a-9fd6-44d1daac1494">

Could we have `flagName` back? I could use the amplitude API to fetch them instead, but was kinda nice to not have to bother amplitude servers with extra requests to get to the flag data.

I'd understand if it was out of scope though, as the server has no need for the name.

**Comment by bgiori** [comment]
Hi @sod,

Unfortunately we're not going to add the name back to the response, as it's not useful for evaluation, which is the primary purpose of this SDK. 

I'd recommend you use the [management API](https://www.docs.developers.amplitude.com/experiment/apis/management-api/) instead.

**Comment by sod** [comment]
Will do. Thanks for the answer :)
