### ISSUE TITLE
Experiment factory is returning the same client when initializing multiple instances

### ISSUE THREAD

**Issue by razvancpop** [amplitude/experiment-node-server#24]
I have an node.js app that is using the Experiment.initialize. I just had a look over the factory that is creating the ExperimentClient. I know the purpose of that is to create a singleton for the client used to fetch experiments. 

So, for my case, I use Experiment.initialize to create multiple clients (each client has his own apiKey associated) but as per current behavior just an instance will be created. To solve this I'm creating my own factory to be able to have multiple instances with different configs/ api keys.

Are you taking in cosideration updating the initialize/initializeRemote implementation to return the ExperimentClient instance based on the API Key? 

https://github.com/amplitude/experiment-node-server/blob/5bbb4387309418f4519f35c554c9d03921284ac6/packages/node/src/factory.ts#L39

**Comment by bgiori** [comment]
Hi @razvancpop, thanks for submitting this issue!

You're right, the current implementation does not allow for multiple instances. We can update this, thanks!

**Comment by razvancpop** [comment]
Thank you @bgiori, I created a PR for this if it's ok for you. 
https://github.com/amplitude/experiment-node-server/pull/25

**Comment by tyiuhc** [comment]
Hi @razvancpop, thanks for raising this issue! The relevant update has been made in v1.7.1
