### ISSUE TITLE
above 1.7.0 version yelling using absolute path

### ISSUE THREAD

**Issue by minhoyooDEV** [amplitude/experiment-node-server#27]
## Expected Behavior

I want it to work well, just like in version 1.6.0.

## Current Behavior

When using the module, it's throwing an error saying that it can't recognize the paths within src.
<img width="683" alt="스크린샷 2023-08-14 오전 11 33 11" src="https://github.com/amplitude/experiment-node-server/assets/18508495/7d578f43-664e-4d5f-8342-410140b8f4e6">

## Possible Solution

absolute path to relative path

## Environment
- JS Server SDK Version: node 16, nextjs 13.1
- Installation Method: yarn berry (workspace) monorepo

**Comment by tyiuhc** [comment]
Hi @minhoyooDEV, thank you so much for raising this issue! This issue has been addressed in v1.7.2.
